name: fourth_task
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publi sh to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  audioplayers: ^0.18.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/colors/
    - assets/images/family_members/
    - assets/images/Numbers/
    - assets/sounds/colors/
    - assets/sounds/numbers/
    - assets/sounds/phrases/
    - assets/sounds/family_members/

